# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install latex packages ğŸ›ï¸
      run: sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended  
   
    - name: Install and Build ğŸ”§
      run: |
        npm install -g gulp-cli
        npm install gulp@3.9.0
        npm i
   
    - name: Deploy ğŸš€
      uses: stefanos1316/programming_blog@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build
